# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 04:19
from __future__ import unicode_literals

from django.db import migrations
from django_rdkit.operations import GiSTIndex


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_application', '0003_add_compound_fingerprint_fields'),
    ]

    operations = [
        GiSTIndex('Compound', 'mfp2')
    ]
