# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_application', '0004_create_compound_mfp2_index'),
    ]

    operations = [
    ]
